name: 'Setup scoop'
description: 'Setup scoop and update PATH for GitHub Actions workflow on Windows environment.'
inputs:
  install_scoop:
    description: 'Install scoop if true (default)'
    required: true
    default: 'true'
  add_extras_bucket:
    description: 'Add extras bucket if true'
    required: true
    default: 'false'
  add_nonportable_bucket:
    description: 'Add nonportable bucket if true'
    required: true
    default: 'false'
  scoop_update:
    description: 'Call scoop update if true (default)'
    required: true
    default: 'true'
  scoop_checkup:
    description: 'Call scoop checkup if true'
    required: true
    default: 'false'
  update_path:
    description: 'Update environment variable PATH for workflow if true (default)'
    required: true
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: 'Setup scoop'
      shell: pwsh
      run: |
        if('${{ inputs.install_scoop }}' -eq 'true') {
            iwr get.scoop.sh -outfile 'install.ps1'
            .\install.ps1 -RunAsAdmin
        }
        if('${{ inputs.update_path }}' -eq 'true') {Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH}
        if('${{ inputs.add_extras_bucket }}' -eq 'true') {scoop bucket add extras}
        if('${{ inputs.add_nonportable_bucket }}' -eq 'true') {scoop bucket add nonportable}
        if('${{ inputs.scoop_update }}' -eq 'true') {scoop update}
        if('${{ inputs.scoop_checkup }}' -eq 'true') {scoop checkup}
