name: 'Setup scoop'
description: 'Setup scoop and update PATH for GitHub Actions workflow on Windows environment.'
inputs:
  install_scoop:
    description: 'Install scoop if true (default)'
    required: true
    default: true
  scoop_update:
    description: 'Call scoop update if true (default)'
    required: true
    default: true
  scoop_checkup:
    description: 'Call scoop checkup if true (default)'
    required: true
    default: false
  update_path:
    description: 'Update environment variable PATH for workflow if true (default)'
    required: true
    default: true
runs:
  using: "composite"
  steps:
    - name: 'Install scoop'
      shell: pwsh
      if: inputs.install_scoop == true
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
        iex (New-Object net.webclient).downloadstring('https://get.scoop.sh')
    - name: 'Install scoop'
      shell: pwsh
      if: inputs.update_path == true
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
        iex (New-Object net.webclient).downloadstring('https://get.scoop.sh')
        (Resolve-Path ~\scoop\shims).Path >> $Env:GITHUB_PATH

