---
name: 'Setup scoop'
description: >-
  Install apps to Windows runner by scoop,
  and update PATH of your workflow.
author: 'MinoruSekine'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  install_scoop:
    description: 'Install scoop if true (default)'
    required: true
    default: 'true'
  scoop_update:
    description: 'Call scoop update if true (default)'
    required: true
    default: 'true'
  scoop_checkup:
    description: 'Call scoop checkup if true'
    required: true
    default: 'false'
  update_path:
    description: >-
      Update environment variable PATH for workflow if true (default)
    required: true
    default: 'true'
  buckets:
    description: 'Bucket(s) to add, delimit several buckets by white space'
    required: false
    default: ''
  custom_buckets:
    description: 'Add bucket(s) by one "name repo-url" pair per line'
    required: false
    default: ''
  run_as_admin:
    description: 'Install scoop with `-RunAsAdmin` or not'
    required: false
    default: 'true'
  apps:
    description: 'Apps to be installed'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: 'Setup scoop'
      shell: pwsh
      run: |
        & $env:ENTRY_POINT_PS1
      env:
        ENTRY_POINT_PS1: ${{ github.action_path }}/scripts/entry_point.ps1
        INSTALL_SCOOP: ${{ inputs.install_scoop }}
        SCOOP_UPDATE: ${{ inputs.scoop_update }}
        SCOOP_CHECKUP: ${{ inputs.scoop_checkup }}
        UPDATE_PATH: ${{ inputs.update_path }}
        BUCKETS: ${{ inputs.buckets }}
        CUSTOM_BUCKETS: ${{ inputs.custom_buckets }}
        RUN_AS_ADMIN: ${{ inputs.run_as_admin }}
        APPS: ${{ inputs.apps }}
