---
name: 'Setup scoop'
description: >-
  Install apps to Windows runner by scoop,
  and update PATH of your workflow.
author: 'MinoruSekine'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  install_scoop:
    description: 'Install scoop if true (default)'
    required: true
    default: 'true'
  scoop_update:
    description: 'Call scoop update if true (default)'
    required: true
    default: 'true'
  scoop_checkup:
    description: 'Call scoop checkup if true'
    required: true
    default: 'false'
  update_path:
    description: >-
      Update environment variable PATH for workflow if true (default)
    required: true
    default: 'true'
  buckets:
    description: 'Bucket(s) to add, delimit several buckets by white space'
    required: false
    default: ''
  run_as_admin:
    description: 'Install scoop with `-RunAsAdmin` or not'
    required: false
    default: 'true'
  apps:
    description: 'Apps to be installed'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: 'Setup scoop'
      shell: pwsh
      run: |
        if($env:INSTALL_SCOOP -eq 'true') {
            if($env:RUN_AS_ADMIN -eq 'true') {
                & "$env:SCRIPTS_PATH\install_scoop.ps1" -ForceAdmin
            } else {
                & "$env:SCRIPTS_PATH\install_scoop.ps1"
            }
            scoop --version
        }
        if($env:UPDATE_PATH -eq 'true') {
            Join-Path (Resolve-Path ~).Path "scoop\shims" >> $Env:GITHUB_PATH
        }
        Write-Host "setup-scoop: inputs.buckets $env:BUCKETS"
        if ($env:BUCKETS) {
            & "$env:SCRIPTS_PATH\add_buckets.ps1" "$env:BUCKETS"
        }
        if($env:SCOOP_UPDATE -eq 'true') {scoop update}
        if($env:SCOOP_CHECKUP -eq 'true') {scoop checkup}
        Write-Host "setup-scoop: inputs.apps $env:APPS"
        if ($env:APPS) {
            & "$env:SCRIPTS_PATH\install_apps.ps1" "$env:APPS"
        }
      env:
        SCRIPTS_PATH: ${{ github.action_path }}\scripts
        INSTALL_SCOOP: ${{ inputs.install_scoop }}
        SCOOP_UPDATE: ${{ inputs.scoop_update }}
        SCOOP_CHECKUP: ${{ inputs.scoop_checkup }}
        UPDATE_PATH: ${{ inputs.update_path }}
        BUCKETS: ${{ inputs.buckets }}
        RUN_AS_ADMIN: ${{ inputs.run_as_admin }}
        APPS: ${{ inputs.apps }}
