---

name: Edge case workflow common parts (reusable workflow)

on:
  workflow_call:
    inputs:
      target:
        description: |
          Workflow target.
          - "dev": HEAD of dev branch
          - "release": latest release tag
          - "pr": PR
        required: true
        type: string

jobs:
  # `apps` parameters tests.
  injection_attack_prevention:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - id: pr
        if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          apps: -foobar
        continue-on-error: true

      - id: dev
        if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: extras
          apps: -foobar
        continue-on-error: true

      - id: release
        if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: extras
          apps: -foobar
        continue-on-error: true

      - if: >-
          ${{
            steps.pr.outcome == 'success' ||
            steps.dev.outcome == 'success' ||
            steps.release.outcome == 'success'
          }}
        run: >-
          Write-Error "${{ github.job }} hasn't been prevented."
          -ErrorAction Stop
        shell: pwsh

  # `buckets` parameter tests.
  illegal_bucket_name:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - id: pr
        if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          buckets: java -add
        continue-on-error: true

      - id: dev
        if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: java -add
        continue-on-error: true

      - id: release
        if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: java -add
        continue-on-error: true

      - if: >-
          ${{
            steps.pr.outcome == 'success' ||
            steps.dev.outcome == 'success' ||
            steps.release.outcome == 'success'
          }}
        run: >-
          Write-Error "${{ github.job }} hasn't been prevented."
          -ErrorAction Stop
        shell: pwsh

  refuse_unknown_bucket:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - id: pr
        if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          buckets: unknown
        continue-on-error: true


      - id: dev
        if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: unknown
        continue-on-error: true

      - id: release
        if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: unknown
        continue-on-error: true

      - if: >-
          ${{
            steps.pr.outcome == 'success' ||
            steps.dev.outcome == 'success' ||
            steps.release.outcome == 'success'
          }}
        run: >-
          Write-Error "${{ github.job }} hasn't been prevented."
          -ErrorAction Stop
        shell: pwsh

  # `run_as_admin` tests.
  GitHub_default_runner_without_RunAsAdmin:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - id: pr
        if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          run_as_admin: false
        continue-on-error: true

      - id: dev
        if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          run_as_admin: false
        continue-on-error: true

      - id: release
        if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          run_as_admin: false
        continue-on-error: true

      - if: >-
          ${{
            steps.pr.outcome == 'success' ||
            steps.dev.outcome == 'success' ||
            steps.release.outcome == 'success'
          }}
        run: >-
          Write-Error "${{ github.job }} hasn't been prevented."
          -ErrorAction Stop
        shell: pwsh

  # Obsoleted parameters tests.
  add_extras_bucket:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - id: pr
        if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          add_extras_bucket: 'true'
        continue-on-error: true

      - id: dev
        if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          add_extras_bucket: 'true'
        continue-on-error: true

      - id: release
        if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          add_extras_bucket: 'true'
        continue-on-error: true

      - name: Validate extras bucket is not available
        shell: pwsh
        run: |
          if([bool](scoop bucket list | Select-String -Quiet "extras")) {
            Write-Error "Unexpected extras bucket found." -ErrorAction Stop
          }

      - if: >-
          ${{
            steps.pr.outcome == 'success' ||
            steps.dev.outcome == 'success' ||
            steps.release.outcome == 'success'
          }}
        run: >-
          Write-Error "${{ github.job }} hasn't been prevented."
          -ErrorAction Stop
        shell: pwsh

  add_nonportable_bucket:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - id: pr
        if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          add_nonportable_bucket: 'true'
        continue-on-error: true

      - id: dev
        if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          add_nonportable_bucket: 'true'
        continue-on-error: true

      - id: release
        if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          add_nonportable_bucket: 'true'
        continue-on-error: true

      - name: Validate nonportable bucket is not available
        shell: pwsh
        run: |
          if([bool](scoop bucket list | Select-String -Quiet "nonportable")) {
            Write-Error "Unexpected nonportable bucket found." -ErrorAction Stop
          }

      - if: >-
          ${{
            steps.pr.outcome == 'success' ||
            steps.dev.outcome == 'success' ||
            steps.release.outcome == 'success'
          }}
        run: >-
          Write-Error "${{ github.job }} hasn't been prevented."
          -ErrorAction Stop
        shell: pwsh
