---

name: Edge case workflow common parts (reusable workflow)

on:
  workflow_call:
    inputs:
      target:
        description: |
          Workflow target.
          - "dev": HEAD of dev branch
          - "release": latest release tag
          - "pr": PR
        required: true
        type: string

jobs:
  validate_inputs_target:
    runs-on: windows-latest
    steps:
      - if: >-
          ${{
            inputs.target != 'pr' &&
            inputs.target != 'dev' &&
            inputs.target != 'release'
          }}
        run: >-
          Write-Error "Unsupported target ${{ inputs.target }}"
          -ErrorAction Stop
        shell: pwsh

  # `apps` parameters tests.
  injection_attack_prevention:
    needs: validate_inputs_target

    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - id: pr
        if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          apps: -foobar
        continue-on-error: true

      - id: dev
        if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: extras
          apps: -foobar
        continue-on-error: true

      - id: release
        if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: extras
          apps: -foobar
        continue-on-error: true

      - if: >-
          ${{
            steps.pr.outcome == 'success' ||
            steps.dev.outcome == 'success' ||
            steps.release.outcome == 'success'
          }}
        run: >-
          Write-Error "${{ github.job }} hasn't been prevented."
          -ErrorAction Stop
        shell: pwsh

  # `buckets` parameter tests.
  illegal_bucket_name:
    needs: validate_inputs_target

    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - id: pr
        if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          buckets: java -add
        continue-on-error: true

      - id: dev
        if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: java -add
        continue-on-error: true

      - id: release
        if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: java -add
        continue-on-error: true

      - if: >-
          ${{
            steps.pr.outcome == 'success' ||
            steps.dev.outcome == 'success' ||
            steps.release.outcome == 'success'
          }}
        run: >-
          Write-Error "${{ github.job }} hasn't been prevented."
          -ErrorAction Stop
        shell: pwsh

  refuse_unknown_bucket:
    needs: validate_inputs_target

    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - id: pr
        if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          buckets: unknown
        continue-on-error: true


      - id: dev
        if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: unknown
        continue-on-error: true

      - id: release
        if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: unknown
        continue-on-error: true

      - if: >-
          ${{
            steps.pr.outcome == 'success' ||
            steps.dev.outcome == 'success' ||
            steps.release.outcome == 'success'
          }}
        run: >-
          Write-Error "${{ github.job }} hasn't been prevented."
          -ErrorAction Stop
        shell: pwsh

  # `run_as_admin` tests.
  # Latest install script of scoop has workaround for GitHub Actions,
  # so RunAsAdmin isn't necessary
  # to install to GitHub Actions default Windows runner.
  GitHub_default_runner_doesnt_need_RunAsAdmin:
    needs: validate_inputs_target

    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          run_as_admin: false

      - if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          run_as_admin: false

      - if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          run_as_admin: false

      - name: Confirm scoop is installed without RunAsAdmin
        shell: pwsh
        run: |
          scoop --version
          if (-not (Get-Command scoop -ErrorAction SilentlyContinue)) {
            Write-Error "scoop was not installed when run_as_admin=false." `
            -ErrorAction Stop
          }
