---

name: Typical usage workflow common parts (reusable workflow)

on:
  workflow_call:
    inputs:
      target:
        description: |
          Workflow target.
          - "dev": HEAD of dev branch
          - "release": latest release tag
          - "pr": PR
        required: true
        type: string

jobs:
  # Typical usage
  default:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./

      - if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main

      - if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2

      - name: Confirm scoop working
        shell: pwsh
        run: scoop bucket list

      - name: Validate no additional buckets are available as default
        shell: pwsh
        run: |
          $buckets = @("extras", "nonportable")
          foreach($bucket in $buckets) {
            if([bool](scoop bucket list | Select-String -Quiet $bucket)) {
              Write-Error "Unexpected `"${bucket}`" bucket." -ErrorAction Stop
            }
          }

  # `buckets` parameter check
  add_extras_bucket_by_buckets_parameter:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          buckets: extras

      - if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: extras

      - if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: extras

      - name: Validate extras bucket is available
        shell: pwsh
        run: |
          if(-Not [bool](scoop bucket list | Select-String -Quiet "extras")) {
            Write-Error "extras bucket not found." -ErrorAction Stop
          }

  add_multiple_buckets_at_once:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          buckets: java games php

      - if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: java games php

      - if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: java games php

      - name: Validate expected buckets are available
        shell: pwsh
        run: |
          $buckets = @("java", "games", "php")
          foreach($bucket in $buckets) {
            if(-Not [bool](scoop bucket list | Select-String -Quiet $bucket)) {
              Write-Error "`"$bucket`" bucket not found." -ErrorAction Stop
            }
          }

  # `custom_buckets` parameter check
  add_multiple_custom_buckets:
    env:
      TEST_TARGET_APPS: win-toast-cli
      # yamllint disable rule:line-length
      TEST_TARGET_REPOS: |
        setup-scoop https://github.com/MinoruSekine/setup-scoop.git
        MinoruSekine https://github.com/MinoruSekine/scoop-bucket-MinoruSekine.git
      # yamllint enable rule:line-length

    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          custom_buckets: ${{ env.TEST_TARGET_REPOS }}
          apps: ${{ env.TEST_TARGET_APPS }}

      - if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          custom_buckets: ${{ env.TEST_TARGET_REPOS }}
          apps: ${{ env.TEST_TARGET_APPS }}

      - name: Validate expected buckets are available
        if: inputs.target == 'pr' || inputs.target == 'dev'
        shell: pwsh
        run: |
          $buckets = @("setup-scoop", "MinoruSekine")
          foreach($bucket in $buckets) {
            if(-Not [bool](scoop bucket list | Select-String -Quiet $bucket)) {
              Write-Error "`"$bucket`" bucket not found." -ErrorAction Stop
            }
          }

  # Install apps check
  install_apps:
    env:
      TEST_TARGET_APPS: "fclones jq xh"

    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          buckets: extras
          apps: ${{ env.TEST_TARGET_APPS }}

      - if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: extras
          apps: ${{ env.TEST_TARGET_APPS }}

      - if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: extras
          apps: ${{ env.TEST_TARGET_APPS }}


      - name: Validate apps are available or not
        shell: pwsh
        run: |
          "${{ env.TEST_TARGET_APPS }}" -split " " | ForEach-Object {
            Get-Command $_ -ErrorAction Stop
          }

  # `update_path` without installing scoop, any buckets, and any apps
  update_PATH_only:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: inputs.target == 'pr'
        uses: actions/checkout@v6

      - if: inputs.target == 'pr'
        name: Run actions locally
        uses: ./
        with:
          install_scoop: 'false'
          scoop_update: 'false'
          scoop_checkup: 'false'
          update_path: 'true'

      - if: inputs.target == 'dev'
        uses: MinoruSekine/setup-scoop@main
        with:
          install_scoop: 'false'
          scoop_update: 'false'
          scoop_checkup: 'false'
          update_path: 'true'

      - if: inputs.target == 'release'
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          install_scoop: 'false'
          scoop_update: 'false'
          scoop_checkup: 'false'
          update_path: 'true'

      - name: Confirm PATH and scoop is unavailable.
        shell: pwsh
        run: |
          if ($Env:Path -notmatch "scoop") {
            Write-Error `
              "PATH environment variable doesn't include path to scoop." `
              -ErrorAction Stop
          }
          if(Get-Command scoop -ErrorAction SilentlyContinue) {
            Write-Error "Unexpectedly found scoop." -ErrorAction Stop
          }
