name: CI

on:
  pull_request:
  schedule:
    - cron:  0 20 1 * *
  workflow_dispatch:

jobs:
  default:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - uses: MinoruSekine/setup-scoop@feature/add_some_processes

    - name: Confirm scoop working
      shell: pwsh
      run: scoop help

  update_PATH_only:
    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v1

    - uses: MinoruSekine/setup-scoop@feature/add_some_processes
      with:
        install_scoop: 'false'
        add_extras_bucket: 'false'
        scoop_update: 'false'
        scoop_checkup: 'false'
        update_path: 'true'

    - name: Confirm PATH and scoop is unavailable.
      shell: pwsh
      run: |
        ($Env:Path -match "scoop")
        if(Get-Command scoop -ErrorAction SilentlyContinue) {Write-Error "Unexpectedly found scoop." -ErrorAction Stop}
