name: CI

on:
  schedule:
    - cron:  0 20 1 * *
  workflow_dispatch:

jobs:
  test-run:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: MinoruSekine/setup-scoop@v1

    - name: Confirm scoop working
      run: |
        scoop update
        scoop checkup
      shell: pwsh
