name: Default usage

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron:  0 8 * * 5
  workflow_dispatch:

jobs:
  default:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4

    - if: ${{ github.event_name == 'pull_request' }}
      name: Run actions locally
      uses: ./

    - if: ${{ github.event_name != 'pull_request' }}
      uses: MinoruSekine/setup-scoop@main

    - name: Confirm scoop working
      shell: pwsh
      run: scoop bucket list

    - name: Validate no additional buckets are available as default
      shell: pwsh
      run: |
        $buckets = @("extras", "nonportable")
        foreach($bucket in $buckets) {
          if([bool](scoop bucket list | Select-String -Quiet $bucket)) {Write-Error "Unexpected `"${bucket}`" bucket is found." -ErrorAction Stop}
        }
