name: Default usage

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 8 * * 1
  workflow_dispatch:

jobs:
  default:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4

      - if: ${{ github.event_name == 'pull_request' }}
        name: Run actions locally
        uses: ./

      - if: >
          ${{ github.event_name == 'push'
          || github.event_name == 'workflow_dispatch' }}
        uses: MinoruSekine/setup-scoop@main

      - if: ${{ github.event_name == 'schedule' }}
        uses: MinoruSekine/setup-scoop@v4.0.2

      - name: Confirm scoop working
        shell: pwsh
        run: scoop bucket list

      - name: Validate no additional buckets are available as default
        shell: pwsh
        run: |
          $buckets = @("extras", "nonportable")
          foreach($bucket in $buckets) {
            if([bool](scoop bucket list | Select-String -Quiet $bucket)) {
              Write-Error "Unexpected `"${bucket}`" bucket." -ErrorAction Stop
            }
          }
