name: Install apps

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 8 * * 1
  workflow_dispatch:

jobs:
  install_app:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4

      - if: ${{ github.event_name == 'pull_request' }}
        name: Run actions locally
        uses: ./
        with:
          buckets: extras
          apps: plantuml doxygen handbrake-cli

      - if: >
          ${{ github.event_name == 'push'
          || github.event_name == 'workflow_dispatch' }}
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: extras
          apps: plantuml doxygen handbrake-cli

      - if: ${{ github.event_name == 'schedule' }}
        uses: MinoruSekine/setup-scoop@v4.0.1
        with:
          buckets: extras
          apps: plantuml doxygen handbrake-cli

      - name: Validate apps are available or not
        shell: pwsh
        run: |
          gcm plantuml
          gcm doxygen

  injection_attack_prevention:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4

      - if: ${{ github.event_name == 'pull_request' }}
        name: Run actions locally
        uses: ./
        with:
          apps: -foobar
        continue-on-error: true

      - if: >
          ${{ github.event_name == 'push'
          || github.event_name == 'workflow_dispatch' }}
        uses: MinoruSekine/setup-scoop@main
        with:
          buckets: extras
          apps: -foobar
        continue-on-error: true

      - if: ${{ github.event_name == 'schedule' }}
        uses: MinoruSekine/setup-scoop@v4.0.1
        with:
          buckets: extras
          apps: -foobar
        continue-on-error: true
