---

name: lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  PSScriptAnalyzer:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: .\scripts\
          recurse: true
          output: psscriptanalyzer.sarif

      - uses: astral-sh/setup-uv@v7.2.0

      - name: Run sarif2gha
        run: |
          uvx --from `
          git+https://github.com/MinoruSekine/sarif2gha.git@abbea6e `
          sarif2gha `
          --project-root-dir="${{ github.workspace }}" psscriptanalyzer.sarif
        shell: pwsh

  YAMLLint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: YAMLLint
        uses: karancode/yamllint-github-action@v3.0.0

  markdown-lint:
    name: Lint markdown files.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: DavidAnson/markdownlint-cli2-action@v22.0.0
