name: Obsoleted parameters

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 8 * * 1
  workflow_dispatch:
    inputs:
      targetVersion:
        description: 'Workflow target'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - v4.0.2

jobs:
  add_extras_bucket:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - if: github.event_name == 'pull_request'
        name: Run actions locally
        uses: ./
        with:
          add_extras_bucket: 'true'
        continue-on-error: true

      - if: >
          (github.event_name == 'push')
          || (github.event_name == 'workflow_dispatch'
              && github.event.inputs.targetVersion == 'main')
        uses: MinoruSekine/setup-scoop@main
        with:
          add_extras_bucket: 'true'
        continue-on-error: true

      - if: >
          (github.event_name == 'schedule')
          || (github.event_name == 'workflow_dispatch'
              && github.event.inputs.targetVersion == 'v4.0.2')
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          add_extras_bucket: 'true'
        continue-on-error: true

      - name: Validate extras bucket is not available
        shell: pwsh
        run: |
          if([bool](scoop bucket list | Select-String -Quiet "extras")) {
            Write-Error "Unexepected extras bucket found." -ErrorAction Stop
          }

  add_nonportable_bucket:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - if: github.event_name == 'pull_request'
        name: Run actions locally
        uses: ./
        with:
          add_nonportable_bucket: 'true'
        continue-on-error: true

      - if: >
          (github.event_name == 'push')
          || (github.event_name == 'workflow_dispatch'
              && github.event.inputs.targetVersion == 'main')
        uses: MinoruSekine/setup-scoop@main
        with:
          add_nonportable_bucket: 'true'
        continue-on-error: true

      - if: >
          (github.event_name == 'schedule')
          || (github.event_name == 'workflow_dispatch'
              && github.event.inputs.targetVersion == 'v4.0.2')
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          add_nonportable_bucket: 'true'
        continue-on-error: true

      - name: Validate nonportable bucket is not available
        shell: pwsh
        run: |
          if([bool](scoop bucket list | Select-String -Quiet "nonportable")) {
            Write-Error "Unexpected nonportable bucket found." -ErrorAction Stop
          }
