name: PR

on:
  pull_request:

jobs:
  default:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: ./

    - name: Confirm scoop working
      shell: pwsh
      run: scoop bucket list

    - name: Validate no additional buckets are available as default
      shell: pwsh
      run: |
        $buckets = @("extras", "nonportable")
        foreach($bucket in $buckets) {
          if([bool](scoop bucket list | Select-String -Quiet $bucket)) {Write-Error "Unexpected `"${bucket}`" bucket is found." -ErrorAction Stop}
        }

  add_extras_bucket:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: ./
      with:
        add_extras_bucket: 'true'

    - name: Validate extras bucket is available
      shell: pwsh
      run: |
        if(-Not [bool](scoop bucket list | Select-String -Quiet "extras")) {Write-Error "extras bucket not found." -ErrorAction Stop}

  update_PATH_only:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: ./
      with:
        install_scoop: 'false'
        add_extras_bucket: 'false'
        add_nonportable_bucket: 'false'
        scoop_update: 'false'
        scoop_checkup: 'false'
        update_path: 'true'

    - name: Confirm PATH and scoop is unavailable.
      shell: pwsh
      run: |
        ($Env:Path -match "scoop")
        if(Get-Command scoop -ErrorAction SilentlyContinue) {Write-Error "Unexpectedly found scoop." -ErrorAction Stop}
