name: run_as_admin

on:
  pull_request:
  schedule:
    - cron:  0 8 * * 5
  workflow_dispatch:

jobs:
  GitHub_default_runner_without_RunAsAdmin:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4

    - if: ${{ github.event_name == 'pull_request' }}
      name: Run actions locally
      uses: ./
      with:
        run_as_admin: false
      continue-on-error: true

    - if: ${{ github.event_name != 'pull_request' }}
      uses: MinoruSekine/setup-scoop@main
      with:
        run_as_admin: false
      continue-on-error: true
