name: run_as_admin

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 8 * * 1
  workflow_dispatch:
    inputs:
      targetVersion:
        description: 'Workflow target'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - v4.0.2

jobs:
  GitHub_default_runner_without_RunAsAdmin:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - if: github.event_name == 'pull_request'
        name: Run actions locally
        uses: ./
        with:
          run_as_admin: false
        continue-on-error: true

      - if: >
          (github.event_name == 'push')
          || (github.event_name == 'workflow_dispatch'
              && github.event.inputs.targetVersion == 'main')
        uses: MinoruSekine/setup-scoop@main
        with:
          run_as_admin: false
        continue-on-error: true

      - if: >
          (github.event_name == 'schedule')
          || (github.event_name == 'workflow_dispatch'
              && github.event.inputs.targetVersion == 'v4.0.2')
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          run_as_admin: false
        continue-on-error: true
