---

name: Typical usage (PR)

on:
  pull_request:

jobs:
  typical_usage:
    uses: ./.github/workflows/_typical_usage.yml
    with:
      target: 'pr'
      os_list_0: '["windows-2025"]'
      os_list_1: '["windows-2022"]'
      os_list_2: '["windows-11-arm"]'
