name: update_path

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 8 * * 1
  workflow_dispatch:
    inputs:
      targetVersion:
        description: 'Workflow target'
        required: true
        default: 'main'
        type: choice
        options:
          - main
          - v4.0.2

jobs:
  update_PATH_only:
    strategy:
      matrix:
        os: [windows-2025, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - if: github.event_name == 'pull_request'
        name: Run actions locally
        uses: ./
        with:
          install_scoop: 'false'
          add_extras_bucket: 'false'
          add_nonportable_bucket: 'false'
          scoop_update: 'false'
          scoop_checkup: 'false'
          update_path: 'true'

      - if: >
          (github.event_name == 'push')
          || (github.event_name == 'workflow_dispatch'
              && github.event.inputs.targetVersion == 'main')
        uses: MinoruSekine/setup-scoop@main
        with:
          install_scoop: 'false'
          add_extras_bucket: 'false'
          add_nonportable_bucket: 'false'
          scoop_update: 'false'
          scoop_checkup: 'false'
          update_path: 'true'

      - if: >
          (github.event_name == 'schedule')
          || (github.event_name == 'workflow_dispatch'
              && github.event.inputs.targetVersion == 'v4.0.2')
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          install_scoop: 'false'
          add_extras_bucket: 'false'
          add_nonportable_bucket: 'false'
          scoop_update: 'false'
          scoop_checkup: 'false'
          update_path: 'true'

      - name: Confirm PATH and scoop is unavailable.
        shell: pwsh
        run: |
          ($Env:Path -match "scoop")
          if(Get-Command scoop -ErrorAction SilentlyContinue) {
            Write-Error "Unexpectedly found scoop." -ErrorAction Stop
          }
