name: Validate @v2 compatibility

on:
  pull_request:
  schedule:
    - cron:  0 8 * * 5
  workflow_dispatch:

jobs:
  default:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4

    - if: ${{ github.event_name == 'pull_request' }}
      name: Run actions locally
      uses: ./

    - if: ${{ github.event_name != 'pull_request' }}
      uses: MinoruSekine/setup-scoop@main

    - name: Confirm scoop working
      shell: pwsh
      run: scoop bucket list

    - name: Validate no additional buckets are available as default
      shell: pwsh
      run: |
        $buckets = @("extras", "nonportable")
        foreach($bucket in $buckets) {
          if([bool](scoop bucket list | Select-String -Quiet $bucket)) {Write-Error "Unexpected `"${bucket}`" bucket is found." -ErrorAction Stop}
        }

  add_extras_bucket:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4

    - if: ${{ github.event_name == 'pull_request' }}
      name: Run actions locally
      uses: ./
      with:
        add_extras_bucket: 'true'

    - if: ${{ github.event_name != 'pull_request' }}
      uses: MinoruSekine/setup-scoop@main
      with:
        add_extras_bucket: 'true'

    - name: Validate extras bucket is available
      shell: pwsh
      run: |
        if(-Not [bool](scoop bucket list | Select-String -Quiet "extras")) {Write-Error "extras bucket not found." -ErrorAction Stop}

  add_nonportable_bucket:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4

    - if: ${{ github.event_name == 'pull_request' }}
      name: Run actions locally
      uses: ./
      with:
        add_nonportable_bucket: 'true'

    - if: ${{ github.event_name != 'pull_request' }}
      uses: MinoruSekine/setup-scoop@main
      with:
        add_nonportable_bucket: 'true'

    - name: Validate nonportable bucket is available
      shell: pwsh
      run: |
        if(-Not [bool](scoop bucket list | Select-String -Quiet "nonportable")) {Write-Error "nonportable bucket not found." -ErrorAction Stop}

  add_multiple_buckets_at_once:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4

    - if: ${{ github.event_name == 'pull_request' }}
      name: Run actions locally
      uses: ./
      with:
        buckets: java games php

    - if: ${{ github.event_name != 'pull_request' }}
      uses: MinoruSekine/setup-scoop@main
      with:
        buckets: java games php

    - name: Validate nonportable bucket is available
      shell: pwsh
      run: |
        $buckets = @("java", "games", "php")
        foreach($bucket in $buckets) {
          if(-Not [bool](scoop bucket list | Select-String -Quiet $bucket)) {Write-Error "`"$bucket`" bucket not found." -ErrorAction Stop}
        }

  illegal_bucket_name:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4

    - if: ${{ github.event_name == 'pull_request' }}
      name: Run actions locally
      uses: ./
      with:
        buckets: java -add
      continue-on-error: true

    - if: ${{ github.event_name != 'pull_request' }}
      uses: MinoruSekine/setup-scoop@main
      with:
        buckets: java -add
      continue-on-error: true

  add_extras_bucket_by_buckets_parameter:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4

    - if: ${{ github.event_name == 'pull_request' }}
      name: Run actions locally
      uses: ./
      with:
        buckets: extras

    - if: ${{ github.event_name != 'pull_request' }}
      uses: MinoruSekine/setup-scoop@main
      with:
        buckets: extras

    - name: Validate extras bucket is available
      shell: pwsh
      run: |
        if(-Not [bool](scoop bucket list | Select-String -Quiet "extras")) {Write-Error "extras bucket not found." -ErrorAction Stop}

  update_PATH_only:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    runs-on: ${{ matrix.os }}

    steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4

    - if: ${{ github.event_name == 'pull_request' }}
      name: Run actions locally
      uses: ./
      with:
        install_scoop: 'false'
        add_extras_bucket: 'false'
        add_nonportable_bucket: 'false'
        scoop_update: 'false'
        scoop_checkup: 'false'
        update_path: 'true'

    - if: ${{ github.event_name != 'pull_request' }}
      uses: MinoruSekine/setup-scoop@main
      with:
        install_scoop: 'false'
        add_extras_bucket: 'false'
        add_nonportable_bucket: 'false'
        scoop_update: 'false'
        scoop_checkup: 'false'
        update_path: 'true'

    - name: Confirm PATH and scoop is unavailable.
      shell: pwsh
      run: |
        ($Env:Path -match "scoop")
        if(Get-Command scoop -ErrorAction SilentlyContinue) {Write-Error "Unexpectedly found scoop." -ErrorAction Stop}
